apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-serviceaccount
  namespace: default
  annotations:
    # The role ARN must match the output from your Terraform configuration (the IRSA role).
    eks.amazonaws.com/role-arn: "arn:aws:iam::533267095186:role/demo-irsa-role"
